[project]
name = "NumpyAndStatsFun"
version = "0.1.0"
description = "Add a short description here"
authors = ["luizzapria <lpria@student.hult.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
scipy = ">=1.13.0,<1.14"
pandas = ">=2.2.2,<2.3"
python = ">=3.12.3,<3.13"
jupyter = ">=1.0.0,<1.1"
numpy = ">=1.26.4,<1.27"
matplotlib = ">=3.8.4,<3.9"
